### ISSUE TITLE
Consider merging both VS Code extensions

### ISSUE THREAD

**Issue by zweimach** [PanAeon/vscode-language-dhall#8]
Thank you so much for creating this wonderful configuration language.

As a user of VS Code and Dhall extensions, I find it quite irritating that I have to install two extensions if I want to get full Dhall support, therefore I have two suggestions:

  - Merge both extensions.
  - Publish the unified extension under the Dhall organization name to indicate that it is an official extension.

If users don't have the language server installed, the extension should fail gracefully, or maybe require manually enable LSP support in the settings.

**Comment by PanAeon** [comment]
@zweimach I have moved both extensions to the `dhall` publisher.
 As for the merging I have the following objection:
A lot of people have either custom dhall language extensions or quite large dhall files. I'm afraid in both cases the lsp server is useless to them and only will irritate  if enabled by default. So the separation of lightweight syntax extension and "heavyweight" lsp extension  seems quite logical to me. Also installing extensions is quite easy, just executing `ext install dhall.dhall-lsp-server` should do the trick, so don't really understand your irritation with it.

 @Gabriel439 if you're ok with this I can make you an owner of the `dhall` publisher in the vscode  marketplace, so you can have control over it. I need your email address and you have to have azure account as described in [publishing extensions](https://code.visualstudio.com/api/working-with-extensions/publishing-extension)

**Comment by Gabriella439** [comment]
My inclination here is to do whatever other popular languages do for VSCode support, so if they typically have a unified extension then we can do that.  I actually thought the two separate extensions was normal because that's the way that Haskell does it (one extension for recognizing and highlighting Haskell files and another one for language server support), but I don't use VSCode and I haven't tried it outside of Haskell.

@PanAeon: Yeah, I will set up an Azure account for the Dhall organization soon.

**Comment by denizdogan** [comment]
@Gabriel439 As an excited newcomer to Dhall, coming from both an Elm and a Haskell background, I was surprised and confused by the various extension options.

I just installed `dhall.dhall-lang`. I looked at `dhall.vscode-dhall-lsp-server` but I was not sure whether it needed some extra configuration or if it would somehow collide with `dhall.dhall-lang`. The LSP server extension mentions  It also says I need to install something using Cabal, which I don't have installed on my system, and even though I enjoy playing around with Haskell once in a while, I'm simply going that far just to install a VSCode plugin for a completely different language.

Honestly, I'd be happy with just `dhall lint --transitive CURRENT_FILE.dhall` being executed when I hit Cmd+Shift+F.

**Comment by Gabriella439** [comment]
@denizdogan: That sounds like the instructions might be misleading since I don't believe you need to build Dhall to use either of the VSCode plugins.  I believe so long as the `dhall-lsp-server` executable is on your `PATH` then they should work, and you can obtain a prebuilt binary for your platform on the release page: https://github.com/dhall-lang/dhall-haskell/releases (Edit: fixed the link)

I haven't had a chance to set up the Azure account to take ownership of this plugin, yet, which is why I haven't made any fixes to the VSCode plugin so far.

**Comment by denizdogan** [comment]
@Gabriel439 Sounds good! However, I was unable to find any prebuilt binaries on the link you sent me, I can only find zip or tar.gz source code.

**Comment by sjakobi** [comment]
@denizdogan: This is the correct link: https://github.com/dhall-lang/dhall-haskell/releases

**Comment by zweimach** [comment]
Thanks for the answer @Gabriel439 @PanAeon. I don't know why I opened this issue while I don't use VS Code for daily coding. You can close this.
